name:                th-extra
version:             0.1.0.0
github:              "githubuser/th-extra"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
- NoImplicitPrelude

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/th-extra#readme>

dependencies:
- base >= 4.7 && < 5
- universum
- template-haskell
- th-abstraction

library:
  source-dirs: src

tests:
  th-extra-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - th-extra
